id = "ty"
name = "Ty"
version = "0.0.1"
schema_version = 1
authors = ["Nathaniel Holden <nholden_ds@icloud.com>"]
description = "Astral ty lsp extension for python"
repository = "https://github.com/NathanielH-snek/ty-zed-extension.git"

[language_servers.ty]
name = "Ty"
languages = ["Python"]